import path from "node:path";
import { fileURLToPath } from "node:url";

export type ResourceDefinition = {
  uri: string;
  title: string;
  description: string;
  mimeType: "text/markdown" | "text/plain";
  kind: "file" | "virtual";
  relativePath?: string;
  virtualText?: string;
};

const currentDir = path.dirname(fileURLToPath(import.meta.url));

export const REPO_ROOT = path.resolve(currentDir, "../../..");

export const RESOURCES: ResourceDefinition[] = [
  {
    uri: "project://index",
    title: "Project Context Index",
    description: "High-level index of available project context resources.",
    mimeType: "text/markdown",
    kind: "virtual",
    virtualText: [
      "# Project Context Index",
      "",
      "- `project://repository-structure`",
      "- `project://technical-spec`",
      "- `project://implementation-notes`",
      "- `project://current-status`",
      "- `project://current-architecture`",
      "- `project://known-limitations`",
      "- `project://testing-status`",
      "- `project://review-flow`"
    ].join("\n")
  },
  {
    uri: "project://repository-structure",
    title: "Repository Structure",
    description: "Curated high-level structure of the repository and main subsystems.",
    mimeType: "text/plain",
    kind: "virtual",
    virtualText: [
      "Repository structure",
      "",
      "Root level",
      "- cmd/api",
      "  Main Go entrypoint for the backend service.",
      "- internal",
      "  Core application code.",
      "- docs",
      "  Assignment source, implementation notes, pseudo-specs, historical progress notes.",
      "- mcp/project-context-server",
      "  Local MCP server with curated project context for coding agents.",
      "- docker-compose.yml",
      "  Local runtime stack: app, postgres, redis, qdrant.",
      "- .ai-spec-review.yml",
      "  Optional project-level review behavior config.",
      "",
      "internal layout",
      "- internal/api/http",
      "  HTTP router, handlers, transport DTOs, status endpoints.",
      "- internal/app",
      "  Dependency wiring and application bootstrap.",
      "- internal/config",
      "  Environment config loading and validation.",
      "- internal/domain",
      "  Core types: document, analysis, finding, review memory, policies.",
      "- internal/service",
      "  Main orchestration layer.",
      "  Look here for analysis flow, comment publishing, inbox polling, memory, async jobs.",
      "- internal/comment",
      "  Human-facing comment formatting for Google Docs.",
      "- internal/parser",
      "  Chunking and document preparation before LLM analysis.",
      "- internal/reviewshape",
      "  Finding taxonomy, issue fingerprints, theme grouping, preferred roles.",
      "- internal/integration/google",
      "  Google Docs reader, Drive comments publisher, Google-specific ingestion logic.",
      "- internal/integration/llm",
      "  LLM client adapters and structured output handling.",
      "- internal/integration/vector",
      "  Embeddings client and Qdrant store.",
      "- internal/repository",
      "  Persistence contracts and implementations.",
      "  Postgres stores durable state, Redis supports cache and async flow.",
      "- internal/jobs",
      "  Async job contracts and worker-facing message types.",
      "- internal/reviewconfig",
      "  Loader and validation for .ai-spec-review.yml.",
      "",
      "Where to look by topic",
      "- Google Docs flow: internal/integration/google + internal/service/comment_service.go + internal/service/google_inbox_service.go",
      "- Analysis pipeline: internal/service/analysis_service.go",
      "- Memory and incremental review: internal/service/review_memory.go + analysis_service.go",
      "- Comment formatting: internal/comment/formatter.go",
      "- Issue shaping and dedup: internal/reviewshape/issues.go",
      "- Vector memory: internal/integration/vector + internal/service/vector_indexer.go",
      "- MCP context server: mcp/project-context-server/src"
    ].join("\n")
  },
  {
    uri: "project://technical-spec",
    title: "Original Technical Specification",
    description: "Original assignment requirements in text form.",
    mimeType: "text/plain",
    kind: "file",
    relativePath: "docs/technical_specification_review_agent.txt"
  },
  {
    uri: "project://implementation-notes",
    title: "Implementation Notes",
    description: "Architecture and implementation notes for the project.",
    mimeType: "text/markdown",
    kind: "file",
    relativePath: "docs/implementation_notes.md"
  },
  {
    uri: "project://current-status",
    title: "Current Status",
    description: "Short current-state snapshot of the project.",
    mimeType: "text/plain",
    kind: "virtual",
    virtualText: [
      "Current status",
      "",
      "Backend MVP is implemented and operational.",
      "",
      "Implemented and exercised in practice",
      "- Google Docs ingestion.",
      "- Role-based review pipeline.",
      "- Structured findings and summary generation.",
      "- Google Docs comment publishing.",
      "- Async analysis lifecycle.",
      "- Incremental rerun by Google Docs command comment.",
      "- Review memory and duplicate suppression between iterations.",
      "- Vector memory foundation with Qdrant indexing.",
      "- MCP project-context server for agent-facing documentation.",
      "",
      "Main unresolved point",
      "- Native inline comments in Google Docs are not treated as an open implementation task.",
      "- Public Google Docs and Drive APIs do not provide a reliable path to the expected native inline UX.",
      "- A grey-area workaround would require extra engineering surface and separate operational resources.",
      "- That path is intentionally not pursued in this project because it is not a sound tradeoff for the current scope.",
      "",
      "Practical interpretation",
      "- The system is in a strong MVP state.",
      "- Remaining work is mostly documentation and optional polish, not missing core backend capability."
    ].join("\n")
  },
  {
    uri: "project://current-architecture",
    title: "Current Architecture",
    description: "Template for a short snapshot of the current backend architecture.",
    mimeType: "text/plain",
    kind: "virtual",
    virtualText: [
      "Current architecture",
      "",
      "Application shape",
      "- Backend is a Go monolith.",
      "- HTTP layer is built on Chi.",
      "- Async execution stays inside the same service process.",
      "",
      "Main runtime components",
      "- HTTP API for analysis creation, polling and comment publishing.",
      "- Analysis orchestration layer for parsing, LLM execution and result shaping.",
      "- Google integration layer for Docs reading and Drive comments publishing.",
      "- Review memory layer for incremental and history-aware review.",
      "- Comment formatter layer for human-facing Google Docs output.",
      "",
      "Persistence and state",
      "- Postgres is the source of truth for documents, analysis runs, findings and artifacts.",
      "- Redis is used for cache and async job coordination.",
      "- Qdrant is an optional separate vector store for semantic memory artifacts.",
      "",
      "External integrations",
      "- LLM provider for role-based review.",
      "- Google Docs API for document content and structure.",
      "- Google Drive API for comments lifecycle.",
      "- OpenRouter embeddings endpoint for vector indexing.",
      "",
      "Analysis model",
      "- Review is role-based.",
      "- Findings are shaped by deterministic backend rules after LLM output.",
      "- Incremental review reuses review memory and suppresses known duplicates.",
      "",
      "Deployment shape",
      "- Docker Compose stack.",
      "- Separate containers for app, postgres, redis and qdrant.",
      "- Nginx terminates external traffic in deployed environment."
    ].join("\n")
  },
  {
    uri: "project://known-limitations",
    title: "Known Limitations",
    description: "Template for current technical and product limitations.",
    mimeType: "text/plain",
    kind: "virtual",
    virtualText: [
      "Known limitations",
      "",
      "Hard platform limits",
      "- Native Google Docs inline comments are not reliably achievable through public Docs/Drive APIs.",
      "- Drive comments can be published, but native inline UX is not guaranteed by the public API surface.",
      "",
      "Current product limitations",
      "- Comments are standard Google Docs comments, not true range-bound native inline annotations.",
      "- Contradiction detection is useful but still heuristic and LLM-dependent, not a deterministic engine.",
      "- Comment author identity in Google Docs is tied to the Google account or service account principal.",
      "",
      "Current quality limitations",
      "- Cross-role dedup is improved but not perfect for every wording variant.",
      "- Summary grouping is deterministic and compact, but still heuristic.",
      "- Some findings can still overlap around nearby product, QA and frontend themes.",
      "",
      "Current technical tradeoffs",
      "- Vector memory is used mainly for indexing foundation; retrieval is not the primary review path yet.",
      "- Review quality relies on prompt discipline plus backend shaping, not on a second judge model.",
      "- Async workers run inside the same monolith process, not as a separate worker service.",
      "",
      "What is intentionally not implemented",
      "- No custom frontend review UI.",
      "- No browser automation layer for Google Docs.",
      "- No heavy semantic clustering or extra LLM judge pass in the core runtime path."
    ].join("\n")
  },
  {
    uri: "project://testing-status",
    title: "Testing Status",
    description: "Template for what has already been tested and what still needs verification.",
    mimeType: "text/plain",
    kind: "virtual",
    virtualText: [
      "Testing status",
      "",
      "Verified end-to-end",
      "- Google Docs intake to published comments flow was tested on real documents.",
      "- Incremental rerun by Google Docs comment command was tested end-to-end.",
      "- Agent-owned comment cleanup before rerun was tested on real Google Docs runs.",
      "- Async analysis flow with queued -> processing -> completed lifecycle was tested.",
      "",
      "Verified manually",
      "- Role-based review output was checked on real pseudo-spec documents.",
      "- Summary compactness, role separation and comment formatting were checked manually.",
      "- Incremental memory behavior was checked by repeated reviews of the same document thread.",
      "- Vector memory indexing to Qdrant was checked on a live environment.",
      "- MCP server startup, resources list and resources read were tested locally.",
      "",
      "Verified by automated tests",
      "- Service layer tests cover analysis flow, dedup, memory behavior, review config and inbox scenarios.",
      "- Comment formatter tests cover role comments, summary grouping and compact formatting.",
      "- Vector store and vector indexer behavior were covered by targeted tests.",
      "- Project builds and targeted Go tests were repeatedly run after major changes.",
      "",
      "Not fully verified",
      "- Vector retrieval as a meaningful input back into review is not a primary tested path yet.",
      "- Contradiction detection is tested at MVP level, but not proven as exhaustive on large document sets.",
      "- Native inline Google Docs comments are not considered a verified path because of platform limits.",
      "",
      "Areas worth rechecking after major changes",
      "- Google Docs publish flow after formatter changes.",
      "- Incremental suppression quality after taxonomy changes.",
      "- Qdrant integration if embedding model or payload schema changes.",
      "- MCP resources whenever curated documentation is updated."
    ].join("\n")
  },
  {
    uri: "project://review-flow",
    title: "Review Flow",
    description: "Template for the end-to-end review pipeline.",
    mimeType: "text/plain",
    kind: "virtual",
    virtualText: [
      "Review flow",
      "",
      "1. Ingest",
      "- Input source is either upload content or Google Docs.",
      "- Google Docs source is normalized to a stable external document id.",
      "",
      "2. Parse and structure",
      "- Document text is extracted.",
      "- For Google Docs, structure metadata is also collected: sections, blocks, ranges.",
      "- Parser prepares normalized content and chunk candidates.",
      "",
      "3. Resolve effective review settings",
      "- Backend loads defaults plus optional .ai-spec-review.yml.",
      "- Effective roles, chunk size, memory usage, severity policy and publish mode are resolved here.",
      "",
      "4. Build analysis context",
      "- For repeated reviews, backend derives review_key.",
      "- Previous runs for the same thread are loaded.",
      "- Compact review memory is prepared for incremental and history-aware review.",
      "",
      "5. Run role-based analysis",
      "- Chunks are reviewed by enabled roles in parallel with bounded concurrency.",
      "- Each role returns structured findings only.",
      "",
      "6. Shape findings",
      "- Backend normalizes severity.",
      "- Duplicate and low-value findings are reduced.",
      "- Findings are grouped by issue fingerprint and preferred role ownership.",
      "",
      "7. Save results",
      "- Analysis run, findings, artifacts and summary are stored.",
      "- Memory snapshot and structure snapshot are saved as artifacts when available.",
      "",
      "8. Publish comments",
      "- If requested, backend formats role comments and summary comment for Google Docs.",
      "- Standard document comments are published through Drive API.",
      "",
      "9. Incremental rerun path",
      "- New comment commands in Google Docs can trigger incremental review.",
      "- Rerun may target a specific section.",
      "- Old agent-owned comments are cleaned up before the new publish cycle.",
      "",
      "10. Memory update",
      "- Current run enriches the review thread history.",
      "- Next incremental pass can reuse prior findings, summaries and structured memory hints."
    ].join("\n")
  }
];

export function getResourceByURI(uri: string): ResourceDefinition | undefined {
  return RESOURCES.find((resource) => resource.uri === uri);
}
