ALTER TABLE analysis_runs
ADD COLUMN IF NOT EXISTS merge_blocked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE analysis_runs
ADD COLUMN IF NOT EXISTS blocking_findings_count INTEGER NOT NULL DEFAULT 0;
