package llm

import (
	"context"

	"technical-specification-review-agent/internal/domain"
)

type PromptInput struct {
	DocumentText string
	Chunks       []string
}

type Client interface {
	Analyze(ctx context.Context, input PromptInput) ([]domain.Finding, string, error)
}

type NoopClient struct{}

func NewNoopClient() *NoopClient {
	return &NoopClient{}
}

func (c *NoopClient) Analyze(_ context.Context, input PromptInput) ([]domain.Finding, string, error) {
	finding := domain.Finding{
		Role:        "solution_architect",
		Category:    "placeholder",
		Severity:    domain.SeverityInfo,
		Problem:     "LLM integration is not wired yet",
		WhyItIsBad:  "The analysis pipeline has no external provider configured.",
		HowToFix:    "Implement a provider-backed client and map findings into domain models.",
		SourceChunk: input.DocumentText,
	}

	return []domain.Finding{finding}, "Placeholder summary generated by the noop LLM client.", nil
}
